services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
      - rabbitmq
    restart: always

  pinger:
    build: ./pinger
    env_file:
      - .env
    depends_on:
      - backend
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  frontend:
    build: ./client
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
