services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always

  pinger:
    build: ./pinger
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  frontend:
    build: ./client
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always
